In [1]:
array_list=[
    [100,65,160],
    [150,82,200],
    [90,55,80],
    [130,73,220],
    [190,80,150]  
]

In [3]:
array_list

[[100, 65, 160], [150, 82, 200], [90, 55, 80], [130, 73, 220], [190, 80, 150]]

In [4]:
array_list[0][2]

160

In [5]:
array_list[3][0]

130

In [10]:
import numpy as np

In [11]:
array_d_dimensiones=np.array(
    [[100,65,160],[100,65,160],[100,65,160]],
    [[150,82,200],[150,82,200],[150,82,200]],
    [[90,55,80],[90,55,80],[90,55,80]],
    [[130,73,220],[130,73,220],[130,73,220]],
    [[190,80,150],[150,82,200],[150,82,200]]  
)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [12]:
array_1d = np.array([1,2,3,4])

In [13]:
array_1d

array([1, 2, 3, 4])

In [15]:
array_2d = np.array([[1,2,3],[4,5,6]])

In [16]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
type(array_2d)

numpy.ndarray

In [18]:
type(array_1d)

numpy.ndarray

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [41]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [21]:
ar=np.arange(5)
ar[::-1]

array([4, 3, 2, 1, 0])

In [22]:
array_1d.dtype

dtype('int32')

In [23]:
array_1d.shape

(4,)

In [25]:
array_1d.ndim

1

In [26]:
array_2d.size

6

In [27]:
array_2d.itemsize

4

In [29]:
array_2d.nbytes

24

In [30]:
array_2d.strides

(12, 4)

In [32]:
# (2,3)
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
np.zeros((3,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [43]:
np.random.rand(4,4)

array([[9.79819621e-01, 5.90633745e-01, 6.76779550e-01, 2.40848230e-01],
       [7.82756784e-01, 6.18534737e-01, 4.51323268e-01, 1.20170859e-01],
       [1.11900754e-04, 5.96714490e-01, 3.08144926e-01, 4.39308710e-01],
       [1.75787698e-01, 3.06012273e-01, 1.26990851e-02, 2.75884330e-01]])

In [44]:
np.random.randn(2,4)

array([[-0.92157698,  0.41170871, -0.04970727, -1.08800401],
       [-0.076064  , -1.21393301,  0.11108344,  0.86971588]])

In [45]:
# matriz 2x4
# media = 10
# desv = 5
5*np.random.randn(2,4)+10


array([[10.81675348,  5.46842715,  7.89694297, 17.12498243],
       [16.13279527, 10.26061053, 10.06274688, 14.60486351]])

In [46]:
# creando una matriz en el rango de 2 a 5

np.random.randint(2,5, (2,3))

array([[3, 3, 2],
       [4, 3, 3]])

In [48]:
arr_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
ar=2*np.arange(6)
ar

array([ 0,  2,  4,  6,  8, 10])

In [52]:
ar[1:5:2]

array([2, 6])

In [53]:
ar[1:6:2]

array([ 2,  6, 10])

In [54]:
ar[:4]

array([0, 2, 4, 6])

In [55]:
ar[4:]

array([ 8, 10])

In [56]:
ar[::3]

array([0, 6])

In [61]:
array_1d**2

array([ 1,  4,  9, 16], dtype=int32)

In [62]:
array_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
array_2d*array_2d

array([[ 1,  4,  9],
       [16, 25, 36]])

In [68]:
array_2d @ array_2d.T

array([[14, 32],
       [32, 77]])

In [69]:
array_2d.sum()

21

In [71]:
array_2d.sum(axis=1)

array([ 6, 15])

In [73]:
array_2d.cumsum()


array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [78]:
np.mean(array_1d)


2.5

In [77]:
array_1d

array([1, 2, 3, 4])

In [81]:
np.median(array_2d)

3.5

In [83]:
np.var(array_2d)

2.9166666666666665

In [85]:
np.std(array_2d)


1.707825127659933

In [88]:
np.mean(array_2d, axis=1)

array([2., 5.])